/* Render the nine-part, source-linked image comparison report. */
(function(root){
const titles={ulna:'척골 원위부',radius:'요골 원위부',femur:'대퇴골 원위부',extra:'추가자료'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function evidence(items){return (items||[]).map(e=>`<details class="citation"><summary>${esc(e.source?.name||e.source_id)} · p.${esc(e.source?.page||'')} · ${esc(e.verification||'')}</summary>${e.quote?`<blockquote>${esc(e.quote)}</blockquote>`:''}<p>${esc(e.explanation)}</p><a class="source-link" href="${esc(e.source?.url||'#')}" target="_blank" rel="noopener">원문 페이지 열기 ↗</a></details>`).join('')}
function claims(items,empty='현재 자료에서 근거를 확인하지 못했습니다.'){return items?.length?items.map(c=>`<div class="report-claim"><p>${esc(c.text)}</p>${c.file_ids.length?`<small>검진파일 ${c.file_ids.map(esc).join(', ')}</small>`:''}${evidence(c.evidence)}</div>`).join(''):`<p>${empty}</p>`}
function age(months){if(months===null||months===undefined)return '';const rounded=Math.round(months);return `${Math.floor(rounded/12)}세 ${rounded%12}개월`}
function value(est,unit){if(est.status!=='estimated')return '판단 보류';const format=n=>unit==='개월'?age(n):`${n} cm`;if(est.center!==null)return format(est.center);if(est.low!==null&&est.high!==null)return `${format(est.low)}–${format(est.high)}`;return '판단 보류'}
function estimate(est,unit){return `<div class="estimate-box"><strong>${esc(value(est,unit))}</strong>${est.status==='estimated'&&est.low!==null&&est.high!==null?`<span>추정범위 ${esc(unit==='개월'?age(est.low):est.low+' cm')} – ${esc(unit==='개월'?age(est.high):est.high+' cm')}</span>`:''}<p>${esc(est.reasoning)}</p>${est.method?`<p><b>방법</b> ${esc(est.method)}</p>`:''}<small>${esc(est.limitation)}</small></div>${evidence(est.evidence)}`}
function heightEstimate(est){return `<p><b>${est.basis==='formula'?'원문 공식 기반 계산':'AI 종합 추정 · 의료진 검토용'}</b></p>${estimate(est,'cm')}${est.operating_range?`<p><b>pre-PHV·가속기 운영 범위</b> ${esc(est.operating_range.low)}–${esc(est.operating_range.high)} cm<br><small>중간값 −1.5 ~ +5.5cm · 사용자 지정 범위</small></p>`:''}<small>추정 구간과 운영 범위는 검증된 확률·신뢰구간이 아닙니다.</small>`}
function section(n,title,body){return `<section class="report-section clinical-section"><h3><span>${n}</span> ${title}</h3>${body}</section>`}
function sportsPlan(r){return r.sports_plan?.paragraphs?.length===3?`<div class="sports-plan">${r.sports_plan.paragraphs.map(p=>`<p>${esc(p)}</p>`).join('')}<small>${esc(r.sports_plan.basis)}</small></div>`:claims(r.sports_integrated)}
function stageLegend(r){return r.mps_stages?.length?`<details class="stage-guide"><summary>MPS 단계 정의</summary><ul>${r.mps_stages.map(s=>`<li>Stage ${esc(s.number)} · ${esc(s.label)}</li>`).join('')}</ul></details>`:''}
function render(ai){const r=ai.clinical_report;return `<div class="clinical-report"><details class="clinical-disclosure"><summary>분석 정보 및 근거</summary><p>${esc(ai.notice)}</p><small>${esc(ai.model)} · AI 요청 ${ai.analysis_passes}회 · 참고 페이지 이미지 ${ai.reference_images}쪽 · 검진 시각자료 ${ai.patient_images}개</small>${ai.usage?`<p><small>실제 사용 토큰: 입력 ${esc(ai.usage.input_tokens)} · 출력 ${esc(ai.usage.output_tokens)} · 캐시 입력 ${esc(ai.cached_tokens||0)}</small></p>`:''}</details><div class="clinical-highlights"><div><span>종합 골연령 추정</span><strong>${esc(value(r.bone_age,'개월'))}</strong></div><div><span>MPS 성장단계</span><strong>${esc(r.phv.label)}</strong></div><div><span>예상 최종키</span><strong>${esc(value(r.adult_height,'cm'))}</strong></div></div>${section(1,'자료 점검',claims(r.data_review))}${section(2,'초음파 부위별 해석',r.regions.map(region=>`<article class="region-reading"><h4>${esc(titles[region.group])}</h4><small>비교 파일: ${region.file_ids.map(esc).join(', ')} · ${esc(region.quality)}</small><p><b>관찰</b> ${esc(region.observation)}</p><p><b>참고영상 비교</b> ${esc(region.comparison)}</p><p class="limitation">${esc(region.limitation)}</p>${evidence(region.evidence)}</article>`).join('')+(r.regions.length?'':'<p>근거와 연결된 부위 판독이 없습니다. 영상의 부위·화질·참고자료 적합성을 확인해주세요.</p>')+`<details><summary>사진별 관찰 ${r.image_readings.length}개</summary>${r.image_readings.map(i=>`<article class="image-reading"><h4>${esc(i.file_id)} · ${esc(i.filename)} · ${esc(titles[i.group])}</h4><span class="report-tag">${{usable:'관찰 가능',limited:'일부 관찰 가능',unusable:'판독 불가'}[i.quality]}</span><ul>${i.observations.map(o=>`<li>${esc(o)}</li>`).join('')}</ul>${i.visible_measurements.length?`<p>영상에 기재된 계측: ${i.visible_measurements.map(esc).join(' · ')}</p>`:''}<p>${esc(i.limitation)}</p></article>`).join('')}</details>`)}${section(3,'종합 뼈나이 추정',estimate(r.bone_age,'개월'))}${section(4,'MPS 성장단계 판정',`<div class="estimate-box"><strong>${esc(r.phv.label)}</strong><small>${esc(r.phv.system)}</small><p>${esc(r.phv.reasoning)}</p><small>${esc(r.phv.limitation)}</small></div>${evidence(r.phv.evidence)}${stageLegend(r)}`)}${section(5,'예상 최종키 · 보조 추정',heightEstimate(r.adult_height))}${section(6,'해석 근거',claims(r.rationale))}${section(7,'한계와 불확실성',`<ul>${r.limitations.map(l=>`<li>${esc(l)}</li>`).join('')}</ul>${ai.rejected_citations?`<p>유효하지 않은 인용 ${ai.rejected_citations}건을 제외했습니다.</p>`:''}`)}${section(8,'추적 관찰 제안',claims(r.follow_up))}${section(9,'스포츠과학 × 스포츠한의학 융합 성장평가',sportsPlan(r))}</div>`}
root.ClinicalRenderer={render,value};
})(globalThis);
