/* Deterministic local parsing. No network or AI call. */
(function(root){
const labels={name:'이름',sex:'성별',birth:'생년월일',exam:'검사일',visit_number:'검사 회차',father_height:'아버님 키',mother_height:'어머님 키',height:'현재 키',weight:'현재 체중',body_fat:'체지방률',ecw_ratio:'ECW-Ratio',previous_bone_age_months:'이전 회차 골연령',previous_stage:'이전 회차 성장단계',previous_predicted_height:'이전 회차 예측키',previous_height:'이전 키',previous_date:'이전 검사일'};
const aliases={'이름':'name','성명':'name','성별':'sex','생년월일':'birth','검사일':'exam','검진일':'exam','측정일':'exam','회차':'visit_number','검사회차':'visit_number','아버님키':'father_height','아버지키':'father_height','부키':'father_height','어머님키':'mother_height','어머니키':'mother_height','모키':'mother_height','현재키':'height','현재신장':'height','신장':'height','현재체중':'weight','체중':'weight','체지방률':'body_fat','ecw-ratio':'ecw_ratio','ecwratio':'ecw_ratio','이전회차골연령':'previous_bone_age_months','이전골연령':'previous_bone_age_months','이전회차성장단계':'previous_stage','이전성장단계':'previous_stage','이전회차예측키':'previous_predicted_height','이전예측키':'previous_predicted_height','이전키':'previous_height','이전신장':'previous_height','이전회차키':'previous_height','이전검사일':'previous_date','이전측정일':'previous_date','이전회차검사일':'previous_date'};
function parse(text){const values={},errors=[],unrecognized=[],seen=new Set();for(const line of text.normalize('NFKC').split(/\r?\n/)){if(!line.trim())continue;const m=line.match(/^\s*([^:]+):\s*(.*?)\s*$/);if(!m){unrecognized.push(line);continue}const field=aliases[m[1].replace(/\s/g,'').toLowerCase()];if(!field){unrecognized.push(line);continue}if(seen.has(field)){errors.push(`${labels[field]} 항목이 중복되어 있습니다. 한 회차의 기록만 붙여넣어주세요.`);delete values[field];continue}seen.add(field);let v=m[2].trim();if(!v){errors.push(`${labels[field]} 값이 비어 있습니다.`);continue}
if(['birth','exam','previous_date'].includes(field)){const d=v.match(/^(\d{4})[-/.년]\s*(\d{1,2})[-/.월]\s*(\d{1,2})\s*(?:일|\.)?$/);if(!d){errors.push(`${labels[field]} 날짜 형식을 확인해주세요.`);continue}const year=+d[1],month=+d[2],day=+d[3],dt=new Date(Date.UTC(year,month-1,day));if(dt.getUTCFullYear()!==year||dt.getUTCMonth()!==month-1||dt.getUTCDate()!==day){errors.push(`${labels[field]}에 유효하지 않은 날짜가 있습니다.`);continue}v=`${year}-${String(month).padStart(2,'0')}-${String(day).padStart(2,'0')}`}
else if(field==='sex'){if(/^(남|남아|남자|남성|male|m)$/i.test(v))v=1;else if(/^(여|여아|여자|여성|female|f)$/i.test(v))v=2;else{errors.push('성별을 남 또는 여로 입력해주세요.');continue}}
else if(field==='previous_bone_age_months'){const a=v.match(/^(\d+)\s*(?:년|세)(?:\s*(\d+)\s*(?:개월|월))?$/),b=v.match(/^(\d+)\s*개월$/);if(a&&+(a[2]||0)<12)v=+a[1]*12+ +(a[2]||0);else if(b)v=+b[1];else{errors.push('이전 골연령은 12년 8개월처럼 입력해주세요. 소수 표기는 자동 해석하지 않습니다.');continue}if(v>240){errors.push('이전 골연령 범위를 확인해주세요.');continue}}
else if(!['name','previous_stage'].includes(field)){const numeric=v.match(/^([0-9]+(?:\.[0-9]+)?)\s*(cm|kg|%|회차|회)?$/i);const units={father_height:'cm',mother_height:'cm',height:'cm',weight:'kg',body_fat:'%',previous_predicted_height:'cm',previous_height:'cm',visit_number:'회차'};if(!numeric||(numeric[2]&&numeric[2].toLowerCase()!==units[field]&&!(field==='visit_number'&&numeric[2]==='회'))){errors.push(`${labels[field]}의 수치와 단위를 확인해주세요.`);continue}v=Number(numeric[1]);const ranges={height:[40,230],weight:[1,250],father_height:[100,230],mother_height:[100,230],body_fat:[0,100],ecw_ratio:[0,1],previous_predicted_height:[40,250],previous_height:[40,230],visit_number:[1,99]};const [lo,hi]=ranges[field];if(v<lo||v>hi||(field==='visit_number'&&!Number.isInteger(v))){errors.push(`${labels[field]} 값이 허용 범위를 벗어났습니다.`);continue}}
values[field]=v}
const followup=['previous_bone_age_months','previous_stage','previous_predicted_height','previous_height','previous_date'].some(k=>k in values);return {values,errors,unrecognized,suggestedVisit:followup?2:1,labels};}
const api={parse,labels,fields:Object.keys(labels)};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.MemoParser=api;
})(typeof globalThis!=='undefined'?globalThis:this);
